# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

splitVector <- function(x, n) {
    .Call(`_RFunctions_splitVector`, x, n)
}

SortXY <- function(x, y) {
    .Call(`_RFunctions_SortXY`, x, y)
}

BinnedAverageX <- function(x, n) {
    .Call(`_RFunctions_BinnedAverageX`, x, n)
}

BinnedAverageY <- function(x, y, n) {
    .Call(`_RFunctions_BinnedAverageY`, x, y, n)
}

BinnedAverage <- function(x, y, n) {
    .Call(`_RFunctions_BinnedAverage`, x, y, n)
}

BinnedBootstrapX <- function(x, n, nboot) {
    .Call(`_RFunctions_BinnedBootstrapX`, x, n, nboot)
}

BinnedBootstrapY <- function(x, y, n, nboot) {
    .Call(`_RFunctions_BinnedBootstrapY`, x, y, n, nboot)
}

BinnedBootstrap <- function(x, y, n, nboot) {
    .Call(`_RFunctions_BinnedBootstrap`, x, y, n, nboot)
}

checkCollinearity <- function(X) {
    .Call(`_RFunctions_checkCollinearity`, X)
}

create_x_lagged <- function(x, p, flag_keep_x = TRUE) {
    .Call(`_RFunctions_create_x_lagged`, x, p, flag_keep_x)
}

roll_AR_checkCollinear <- function(y, x, p, window_size) {
    .Call(`_RFunctions_roll_AR_checkCollinear`, y, x, p, window_size)
}

roll_AR_with_constant_checkCollinear <- function(y, x, p, window_size) {
    .Call(`_RFunctions_roll_AR_with_constant_checkCollinear`, y, x, p, window_size)
}

roll_reg_withNo_constant <- function(y, x, window_size) {
    .Call(`_RFunctions_roll_reg_withNo_constant`, y, x, window_size)
}

roll_reg_with_constant <- function(y, x, window_size) {
    .Call(`_RFunctions_roll_reg_with_constant`, y, x, window_size)
}

roll_reg_with_constant_faster <- function(y, x, window_size) {
    .Call(`_RFunctions_roll_reg_with_constant_faster`, y, x, window_size)
}

roll_reg_with_constant_faster_checkCollinear <- function(y, x, window_size) {
    .Call(`_RFunctions_roll_reg_with_constant_faster_checkCollinear`, y, x, window_size)
}

rowMins_local <- function(x) {
    .Call(`_RFunctions_rowMins_local`, x)
}

winsorize <- function(x, lower_cutoff, upper_cutoff) {
    .Call(`_RFunctions_winsorize`, x, lower_cutoff, upper_cutoff)
}

winsorize_quantiles <- function(x, lower_quantile, upper_quantile, print_quantiles = FALSE) {
    .Call(`_RFunctions_winsorize_quantiles`, x, lower_quantile, upper_quantile, print_quantiles)
}

winsorize_one_sided <- function(x, cutoff, lower, print_cutoff = FALSE) {
    .Call(`_RFunctions_winsorize_one_sided`, x, cutoff, lower, print_cutoff)
}

winsorize_one_sided_quantile <- function(x, quantile, lower, print_cutoff = FALSE) {
    .Call(`_RFunctions_winsorize_one_sided_quantile`, x, quantile, lower, print_cutoff)
}

